name: Checks
on: [ pull_request ]
jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
    - name: PHPUnit tests
      uses: php-actions/phpunit@v3
      with:
        configuration: phpunit.xml
        memory_limit: 256M
        php_version: 8.1